[2024-11-30 02:52:52] local.ERROR: Error creating movement - SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint "lc_movimento_pkey"
DETAIL:  Key (id)=(8) already exists. (Connection: pgsql, SQL: insert into "lc_movimento" ("dia", "mes", "ano", "tipo", "categoria", "descricao", "valor") values (30, 11, 2024, entrada, 37, lllll, 99) returning "id")  
